### ISSUE TITLE
Multiple source download stuck at 100% with "connecting" after finishing

### ISSUE THREAD

**Issue by Searinox** [zlatinb/muwire#77]
Downloaded a file worth a few hundred megabytes from what MuWire said were 5 active sources, all which were listed on the search page where it was found.

The file finished its download and everything in the Incomplete Downloads folder was cleared out and the file in question appeared in the Completed Downloads folder with full name and integrity indicating that it was complete.

However, the download task for the file remained, displaying 100% completion, 0 B/s download speed, and a status of "Connecting". I wanted a few minutes to see if it disappeared but it did not. I canceled it.

Cancelling the task left the downloaded file intact and did not remove it but at least it made the download task go away. I was also able to confirm that the file is integral because it had a publicly-known hash.

In Settings -> GUI I have set to automatically clear both cancelled and finished downloads. And indeed right up to that point every download I ever completed or canceled always disappeared from the list.

I mention here that I was using the GitHub65-7 version you posted yesterday, where I know some download logic was changed in order to accomodate for directory downloads. This download however, was not a directory download. It was a single file.

**Comment by Searinox** [comment]
I attempted to reproduce this and although I couldn't, I now have the download/upload speed tracker at the bottom stuck at a non-zero value. The counter is indicating a specific KB/s download speed that is exactly a certain value to the decimal, never changing even slightly, despite me having no ongoing downloads.

**Comment by zlatinb** [comment]
The download being stuck at 100% and the counter being stuck at non-zero value are quite worrying.  I suspect the download object still exists in memory, although it should be disposed after it's been cleared from the downloads table.

If you have not yet restarted MuWire since the counter got stuck, do the following:
1. open a command prompt
2. type `jps -m`.  That will print something like:
```
12345 Jps -m
67890 Launcher
<possibly more lines>
```
3. Get the number of the line containing `Launcher` - this is the process id of the MuWire process.  You can verify this with the windows task manager, although there it would appear as "OpenJDK platform binary" or something like that.
4. type `jmap -histo:live <the number from step 3>`.  This will print a long table of statistics for the different objects in memory.  You want to look for a line containing `NetworkDownloader`.  That is the object that represents a download task.  If there are no download tasks listed in the UI but a non-zero count of NetworkDownloaders, then we have a memory leak.
5. If there is a memory leak, execute `jmap -dump:live,format-b,file=muwire-heap.bin <number from step 3>`.  This will save all the objects in memory to a file called `muwire-heap.bin`.  Once that file is saved, we can analyze it with different tools and you can restart MuWire if you wish.

I'm not going to go into details how to analyze the heap dump yet, will do that if we confirm there is a leak.

**Comment by Searinox** [comment]
I started VisualVM and loaded the heap bin file. I then filtered the objects and found com.muwire.core.download.NetworkDownloader#1. I expanded and looked around the Fields and References. What do I do?

**Comment by zlatinb** [comment]
While the object is selected click on the `GC Root` tab.  This will open a new panel below the table of objects; click on "Compute GC Root" (or something like that).  This will take a while but will eventually populate the new panel with a tree structure that starts with the NetworkDownloader object and goes down to some other object.  

I need to see the entire path from the NetworkDownloader to the object at the bottom of the tree, so either take a screenshot or transcribe it here.  Thanks!

**Comment by Searinox** [comment]
This is what I have:
![image](https://user-images.githubusercontent.com/5074487/136669107-468357b5-797d-457b-9e02-86cb516ea89f.png)

**Comment by zlatinb** [comment]
I was just about to ask that very question... looks like the reference to the downloader object is stuck in the UI.  I need to look around the code some more, but while you still have the snapshot loaded, expand the all the `references` to the NetworkDownloader a few levels and see if there is a `DownloadManager` listed.

Also, if you still haven't restarted, check for any errors in the logs.

**Comment by zlatinb** [comment]
I think this is a rare race condition that occurs when a download is finishing, but a new download worker is starting at the same time.  Can you go over the `fields` of each DownloadWorker and see the value of the field `currentState`.  If everything was fine all workers would point to the same instance of the `WorkerState` class, but I expect at least one of them to point to a different `WorkerState` instance than the others.

**Comment by Searinox** [comment]
Every worker's currentState was FINISHED. However, I did also see this:
![image](https://user-images.githubusercontent.com/5074487/136670663-04b77096-71c2-4928-9da1-734171deb681.png)
Is it of any relevance?

**Comment by zlatinb** [comment]
Interesting, "cancel" is a method and shouldn't be visible there.  Can you expand that node a few levels?

**Comment by Searinox** [comment]
![image](https://user-images.githubusercontent.com/5074487/136671407-0e903254-0561-419f-bef3-8be4ced3d590.png)
I want to mention that there is no stop_closure 7 anywhere that I could find.

**Comment by zlatinb** [comment]
`stop_closure_7` is a method generated during runtime by the Groovy language.  I don't think it's relevant to our case.

I just committed something that should help in the situation where the resume timer fires exactly while the download is finishing.  A build is available at https://muwire.com/downloads/MuWire-0.8.9-GitHub77.zip

**Comment by Searinox** [comment]
I have set the retry timer to one second and set up the new version 77 from your comment and will now proceed to search for high-user download files to test with. I'll know if I see the download counter stuck again. In that case, I will run the JDK commands again and take a look at the new heap. I'll update you if I find anything or if I run enough tests without repro success to warrant reporting on.

**Comment by Searinox** [comment]
Mini update: I actually found and tried the initial offending file again and no matter what I couldn't get it to show up in downloads. Turns out it was also stuck in downloads.json. Maybe that will give you further ideas about where in the code it hanged since it was after the download completing. the parts in the incomplete folder being removed, and the final file being produced, but before its removal from downloads.json.

**Comment by Searinox** [comment]
Okay so; I have something for you:

I found a particular file with 3-4 Direct Sources and 4-6 Possible Sources.

Do you remember when I was downloading files from myself and it first obtained the Hash List and then it disappeared but it was still in downloads.json and resumed on next restart? Well, this case, it goes like this: it gets the hash list, disappears, but does NOT resume correctly on next startup. It remains gone and when I try to download it again, it again gets the hash list for some reason, and then again does nothing.

I know MuWire can share the files it downloads automatically. I do NOT have this option enabled and I did NOT have it on at the time of the incident. Furthermore I absolutely positively do NOT have this file saved on disk anymore from the previous attempt. I have deleted it. The Incomplete Downloads folder is also empty. I also do not for any reason appear listed as one of the many download sources in the search, so this isn't it.

So it's similar to then but different in that it doesn't actually successfully resume ever. And that it's affecting files I'm not sharing.

And now for the really bizzare part: I appear to have 100% repro with this file. I closed down MuWire, cleared out downloads.json and even checked Task Manager to make sure there isn't any zombie instance stuck. I then start again clean, make the search, find the file, try to download it. And it gets stuck after the Hash List. This is NOT what happened the first time around when it actually completed before remaining in limbo like this. But now everytime I try to download it the result is the same.

I'm not sure if this is related to your update 77 but other files with similar source counts and size download just fine.

How are these hashes calculated? The hash for this file is conspicuously short, it has only 56 characters in length in downloads.json.

The entry is like this:

{
	"file": "<56 CHAR HASH>",
	"length": <NUMBER>,
	"pieceSizePow2": <NUMBER>,
	"destinations": [<5 USER IDS>],
	"incompletes": "<VALUE>",
	"hashList": <SINGLE STRING, ~68000 CHARACTERS IN LENGTH>,
	"paused": false,
	"sequential": false
}

I laid it out for visual effect, it's written as a single line in the file.

**Comment by zlatinb** [comment]
Just a while ago I made a commit and referenced issue #65 in it because as part of the changes to preserve folder structure when downloading I broke resuming of downloads after restart.  If you shut down MW while any downloads are happening, not just this weird one, they will not resume on next restart.  This is fixed in 77-2 https://muwire.com/downloads/MuWire-0.8.9-GitHub77-2.zip

About the fields of the `downloads.json`:
* `file` is not a hash, it's Base64-encoded UTF-8 representation of the absolute path of the file on the filesystem.  This is done to avoid having to escape strings in the json representation.
* `hashList` is a Base64-encoded representation of the hashes of each piece of the file.  That string gets decoded into a byte array and every 32 bytes represent a hash of a piece of the file
* `hashRoot` can exist only if `hashList` isn't there yet.  That is Base64-encoded hash of the list of hashes.  When MW downloads the Hash List at the beginning of the download, this field gets removed from `downloads.json`

So please try 77-2 and let me know if the weird file still causes problems.  If it does, we'll investigate further.

**Comment by Searinox** [comment]
I set it up. I'm running it now. I started the offending download, same behavior. I started another download and that one worked. I closed and restarted MuWire. The 2nd download resumed. The offending download never reappeared. I canceled the 2nd download. The offending download is still showing in download.json. I don't know what makes this one so special. The filename is very normal, no exotic path, no incomplete parts, nothing with it or a similar name in the completed download folder.

**Comment by zlatinb** [comment]
Let's turn on some logging then:
```
com.muwire.core.download.level=FINE
```

With that setting try restarting without any changes to `downloads.json`.  If anything shows up in the logs let me know.

If nothing shows in the logs, stop MW, delete `downloads.json`, restart MW and try to download the offending file from a search result or browse host.  There should be lots of things in the log at various levels.  It's best if I can see the entire log, unless you can make out what is wrong right away.

**Comment by Searinox** [comment]
Does this look like it?

2021-10-09 21:48:40.729 WARNING java_util_logging_Logger$log$6 call Hard disconnecting, remove? true on [Connection <VALUE1>/unknown to <VALUE2>.b32.i2p up 1487ms wsize: 3 cwin: 3 rtt: 0 rto: 9000 unacked out: 1 unacked in: 0 sent: 1 rcvd: 0 ackThru -1 ssThresh 64 minRTT 2147483647 maxWin 128 MTU 1812] 
java.lang.Exception: cause
	at net.i2p.client.streaming.impl.Connection.disconnect(Connection.java:785)
	at net.i2p.client.streaming.impl.Connection.disconnect(Connection.java:739)
	at net.i2p.client.streaming.impl.I2PSocketManagerFull.connect(I2PSocketManagerFull.java:594)
	at net.i2p.client.streaming.impl.I2PSocketManagerFull.connect(I2PSocketManagerFull.java:648)
	at net.i2p.client.streaming.I2PSocketManager$connect$3.call(Unknown Source)
	at com.muwire.core.connection.I2PConnector.connect(I2PConnector.groovy:17)
	at com.muwire.core.connection.I2PConnector$connect.call(Unknown Source)
	at com.muwire.core.download.NetworkDownloader$DownloadWorker.run(NetworkDownloader.groovy:345)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by zlatinb** [comment]
Is there no line at INFO level that says something like
```
[timestamp] ... INFO ... will request piece X from position Y steal [true/false]
```

If not, then something is wrong with the remote node, and I will need put together a build with more logging.

**Comment by zlatinb** [comment]
Oh, I think I know what went wrong.  Stop MW, delete `downloads.json` and `mesh.json`, then try the download again.  Let me know if that works and I'll explain what is happening.

**Comment by Searinox** [comment]
Okay I emptied out both downloads.json and mesh.json and now the download started normally.

**Comment by zlatinb** [comment]
Phew ok so this problem was caused by the initial problem - that the download didn't go to "Finished" state when it reached 100%.  

The file `mesh.json` contains a list of which pieces have been fully downloaded and that information is used to decide which piece to request next.  There is one possible path through the code where nothing gets logged if we already have all the pieces the remote has side has.  Since MW thought that it already has all the pieces of the file according to `mesh.json` it decided that the remote side doesn't have any pieces it was interested in.  That is a valid scenario when uploading files which are still being downloaded.

So, now that I think of it I remember seeing a bug with trying to download the same file twice, this would explain it.

**Comment by Searinox** [comment]
This sounds like you should be able to nail it now. The download completed without issue but at this point it won't mean anything. I'll queue several other multiple-source downloads and see if that plus the 1 second retry produces anything.

**Comment by Searinox** [comment]
After many attempts I wasn't able to reproduce this. It's up to you whether you want it to stay open or close it and reopen or make a new one if it happens again.

**Comment by zlatinb** [comment]
Ok.  I'm going to close it mostly because I want to clean up the list of open issues before the release this/next week.
